package org.anadoxin.mailconfig;

import org.anadoxin.mailconfig.boot.Log;
import org.apache.commons.io.*;
import java.io.*;

public class FetchmailRenderer extends AbstractRenderer {
    public void log(String fmt, Object... args) {
        String s = String.format(fmt, args);
        Log.put("[fetchmail] %s", s);
    }

    public void invoke() {
        try {
            doInvoke();
        } catch(FileNotFoundException e) {
            log("File not found error: %s", e.getMessage());
        }
    }

    public void doInvoke() throws FileNotFoundException {
        for(String accountName: mc.getAccountList()) {
            UserAccount acc = mc.getAccountByName(accountName);
            ServerInfo si = mc.getServerByName(acc.getServer());

            String configFilePath = acc.getOption("configfile");

            new File(FilenameUtils.getFullPath(configFilePath)).mkdirs();

            PrintWriter pw = new PrintWriter(new BufferedWriter(new OutputStreamWriter(new FileOutputStream(configFilePath))));
            pw.printf("#\n");
            pw.printf("# Configuration for account %s\n", acc.getName());
            pw.printf("# It has been automatically generated by MailConfig, so editing this file is futile.\n");
            pw.printf("#\n\n");
            pw.printf("set logfile \"%s\"\n", acc.getOption("logfile"));
            pw.printf("poll %s protocol %s", si.getHostName(), si.getProtocol());

            String interval = acc.getOption("interval");
            if(interval.compareTo("1") != 0) {
                pw.printf(" interval %s", interval);
            }

            pw.printf("\n");

            pw.flush();
        }
    }
}
